### ISSUE TITLE
Ironman Icon Issue

### ISSUE THREAD

**Issue by Coreys-Cutz** [Yenof/chat-panel#12]
When speaking to my friend in private chat where the helmet would normally be im getting a <img=2> is this normal and is there any way to fix this

**Comment by Yenof** [comment]
Hello, 
I thought I had filtered out situations where it does that, hopefully it only shows up in private chat.
This is something I will have to fix on my end.
Thank you very much for bringing it to my attention. :)

**Comment by Coreys-Cutz** [comment]
> Hello, I thought I had filtered out situations where it does that, hopefully it only shows up in private chat. This is something I will have to fix on my end. Thank you very much for bringing it to my attention. :)

![image](https://github.com/user-attachments/assets/1122c665-412f-4c60-bd83-3e8b71e66718)
i threw yah a screenshot just figured give yah a visual

**Comment by Yenof** [comment]
That is helpful, thank you.

**Comment by Coreys-Cutz** [comment]
one last thing it seems to only happen in solely the "private chat tab" itself i created a "custom tab" with "private only" and it does not do it, nor will it do it in the "all" chat tab either so I'll just roll with the custom tab for now

**Comment by Yenof** [comment]
Oh sweet, that's awesome to hear that it might me limited to the private chat tab. Thanks for narrowing that down for me. :)

**Comment by Coreys-Cutz** [comment]
Np! Awesome plugin in btw finally can hide chat in fixed mode and have that to side GENIUS!

**Comment by Yenof** [comment]
I'm so glad to hear you like it, thank you so much! :)

**Comment by Yenof** [comment]
Okay I was able to recreate and fix this issue. :D

Should be [fixed](https://github.com/Yenof/chat-panel/commit/acc27e12a8dede765d6d5f9a1eeda898913fbb4b) when the next version comes out, not sure when that will be, there are a lot of new features haha.

I thought there was a reason I had PrivateChat (in) using event.getName(), but I guess not, seems to work great when it is uses the same CleanedName as everything else.

Sorry about this oversight and thanks so much for bringing it to my attention! :D

**Comment by Yenof** [comment]
Good day! 

Chat Panel has been updated to version 2.0, and I believe this issue to be fixed. 

Thanks again for letting me know about this problem. :)
